In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
data = load_breast_cancer()
X,y = load_breast_cancer(return_X_y=True)

In [4]:
col = data['feature_names']
X = pd.DataFrame(X, columns=col)
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [5]:
y = pd.DataFrame(y, columns=['target'])
y

target
0         0
1         0
2         0
3         0
4         0
..      ...
564       0
565       0
566       0
567       0
568       1

[569 rows x 1 columns]

In [6]:
X.shape

(569, 30)

In [7]:
scaler = StandardScaler()
X = scaler.fit_transform(X)
X = pd.DataFrame(X, columns=col)

bias = pd.DataFrame(np.ones((X.shape[0],1)), columns=['bias'])
X = pd.concat((bias,X), axis=1)

In [8]:
df = pd.concat((X,y),axis=1)
df.head()

bias  mean radius  mean texture  mean perimeter  mean area  \
0   1.0     1.097064     -2.073335        1.269934   0.984375   
1   1.0     1.829821     -0.353632        1.685955   1.908708   
2   1.0     1.579888      0.456187        1.566503   1.558884   
3   1.0    -0.768909      0.253732       -0.592687  -0.764464   
4   1.0     1.750297     -1.151816        1.776573   1.826229   

   mean smoothness  mean compactness  mean concavity  mean concave points  \
0         1.568466          3.283515        2.652874             2.532475   
1        -0.826962         -0.487072       -0.023846             0.548144   
2         0.942210          1.052926        1.363478             2.037231   
3         3.283553          3.402909        1.915897             1.451707   
4         0.280372          0.539340        1.371011             1.428493   

   mean symmetry  ...  worst texture  worst perimeter  worst area  \
0       2.217515  ...      -1.359293         2.303601    2.001237   
1       0.001392  ...      -0.369203         1.535126    1.890489   
2       0.939685  ...      -0.023974         1.347475    1.456285   
3       2.867383  ...       0.133984        -0.249939   -0.550021   
4      -0.009560  ...      -1.466770         1.338539    1.220724   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0          1.307686           2.616665         2.109526              2.296076   
1         -0.375612          -0.430444        -0.146749              1.087084   
2          0.527407           1.082932         0.854974              1.955000   
3          3.394275           3.893397         1.989588              2.175786   
4          0.220556          -0.313395         0.613179              0.729259   

   worst symmetry  worst fractal dimension  target  
0        2.750622                 1.937015       0  
1       -0.243890                 0.281190       0  
2        1.152255                 0.201391       0  
3        6.046041                 4.935010       0  
4       -0.868353                -0.397100       0  

[5 rows x 32 columns]

In [9]:
df['target_new'] = df['target'].replace(0,-1)
df['target_new'].unique()

array([-1,  1])

In [10]:
y_new = df['target_new']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y_new, test_size=0.2, random_state=0)

In [12]:
W = np.zeros((X.shape[1]))
W

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
X_train = X_train.to_numpy()
y_train = y_train.to_numpy()
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()

### Perceptron Algorithm


In [14]:
for t in range(500):
    for i in range(X_train.shape[0]):
        affine = np.dot(np.array(X_train[i]),W)
        if affine >= 0:
            y_pred = 1
        else:
            y_pred = -1
        if y_pred != y_train[i]:
            W += y_train[i]*X_train[i]


In [15]:
def predict(X):
    linear_output = np.dot(X, W)
    return np.where(linear_output >= 0, 1, -1)


predictions = predict(X_test)
accuracy = np.mean(predictions == y_test)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 96.49%


### Gradient Descent Algorithm

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train = X_train.to_numpy()
y_train = y_train.to_numpy()
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()

In [48]:
learning_rate= 0.1
max_iter = 1000
weights = np.zeros((X_train.shape[1],1))
weights

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [49]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x)) 

In [51]:
for t in range(max_iter):
    summation = 0
    linear = np.dot(X_train, weights)
    y_pred = sigmoid(linear)

    summation += np.dot(X_train.T, (y_train-y_pred))
    
    dw = -summation/X_train.shape[0]

    weights -= learning_rate*dw             


In [57]:
def predict(X):
    linear_output = np.dot(X, weights)
    linear_output = np.array(list(map(sigmoid, linear_output)))
    return np.where(linear_output >= 0.5, 1, 0.)

predictions = predict(X_test)
accuracy = np.mean(predictions == y_test)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 96.49%
